"""empty message

Revision ID: 1f2bd40e2d9d
Revises: dcf238b601b0
Create Date: 2024-05-13 10:39:40.407915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f2bd40e2d9d'
down_revision = 'dcf238b601b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_title', sa.String(length=255), nullable=False))
        batch_op.drop_column('topic_table')
        batch_op.drop_column('user_lname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_lname', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('topic_table', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('topic_title')

    # ### end Alembic commands ###
