"""empty message

Revision ID: dcf238b601b0
Revises: 8e28822da4c6
Create Date: 2024-05-13 09:58:00.595273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf238b601b0'
down_revision = '8e28822da4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('topic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_table', sa.String(length=100), nullable=False),
    sa.Column('user_lname', sa.String(length=100), nullable=False),
    sa.Column('topic_image', sa.Text(), nullable=True),
    sa.Column('topic_date', sa.DateTime(), nullable=True),
    sa.Column('topic_status', sa.Enum('1', '0'), server_default='0', nullable=False),
    sa.Column('topic_levelid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_levelid'], ['level.level_id'], ),
    sa.PrimaryKeyConstraint('topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    # ### end Alembic commands ###
